# Generated by Django 3.2.16 on 2023-01-10 12:55

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carearticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=190, unique=True)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('article_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('article_excerpt', models.TextField(blank=True)),
                ('articel_content', models.TextField()),
                ('approved_status', models.IntegerField(choices=[(0, 'Content Not Checked'), (1, 'Content Checked for Publishing')], default=0)),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_posts', to=settings.AUTH_USER_MODEL)),
                ('bookmarks', models.ManyToManyField(blank=True, default=None, related_name='bookmark', to=settings.AUTH_USER_MODEL)),
                ('helpful_ticks', models.ManyToManyField(blank=True, related_name='carearticle_tick', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Article_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('article_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='adviceapp.carearticle')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
