# Generated by Django 3.2.16 on 2023-01-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carearticle',
            old_name='articel_content',
            new_name='content',
        ),
    ]
